#@ load("@ytt:data", "data")
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: kubeapps
  namespace: kubeapps
spec:
  commonName: #@ data.values.kubeapps_hostname
  dnsNames:
  - #@ data.values.kubeapps_hostname
  issuerRef:
    kind: ClusterIssuer
    name: mkcert
  secretName: kubeapps-tls