resources:
- name: spring-petclinic
  type: git
  source:
    uri: https://github.com/techgnosis/spring-petclinic.git
    branch: demo
- name: tanzu-gitops
  type: git
  source:
    uri: https://github.com/techgnosis/tanzu-gitops.git
    branch: master
    paths:
     - "concourse/tasks/**"
- name: spring-petclinic-image
  type: docker-image
  source:
    repository: ((harbordomain))/library/spring-petclinic
    tag: latest
    ca_certs:
    - domain: ((harbordomain))
      cert: |
        ((tanzu-gitops.ca_cert))
- name: concourse-helper
  type: docker-image
  source:
    repository: ((harbordomain))/library/concourse-helper
    tag: 1
    ca_certs:
    - domain: ((harbordomain))
      cert: |
        ((tanzu-gitops.ca_cert))

  


jobs:
- name: Build with TBS
  public: true
  serial: true
  plan:
  - get: spring-petclinic
    trigger: true
  - get: concourse-helper
  - get: tanzu-gitops
  - task: handoff to TBS
    image: concourse-helper
    file: tanzu-gitops/concourse/tasks/build-spring-petclinic-image/build-spring-petclinic-image.yml
    params:
      tkgicluster: cluster1
      tkgiapi: ((tanzu-gitops.tkgi_url))
      tkgiuser: ((tanzu-gitops.tkgi_user))
      tkgipassword: ((tanzu-gitops.tkgi_password))



- name: Deploy to cluster
  public: true
  serial: true
  plan:
    - get: spring-petclinic-image
      trigger: true
    - get: tanzu-gitops
    - get: concourse-helper
    - task: handoff to Kubernetes
      file: tanzu-gitops/concourse/tasks/deploy-spring-petclinic-image/deploy-spring-petclinic-image.yml
      image: concourse-helper
      params:
        tkgicluster: cluster1
        tkgiapi: ((tanzu-gitops.tkgi_url))
        tkgiuser: ((tanzu-gitops.tkgi_user))
        tkgipassword: ((tanzu-gitops.tkgi_password))
        harbordomain: ((harbordomain))
    - task: create wavefront event
      image: concourse-helper
      file: tanzu-gitops/concourse/tasks/create-wavefront-event/create-wavefront-event.yml
      params:
        WAVEFRONT_API_TOKEN: ((tanzu-gitops.wavefront_api_token))
        WAVEFRONT_URL: ((tanzu-gitops.wavefront_url))


