apiVersion: kp.kpack.io/v1alpha1
kind: DependencyDescriptor
defaultClusterBuilder: full
defaultStack: full
stores:
- name: default
  sources:
  - image: registry.pivotal.io/tanzu-go-buildpack/go@sha256:b3aabeec621a74bb57c7b97ad5e3d8ee31a83ab367a47455a9aaac7b79cbc022
  - image: registry.pivotal.io/tanzu-java-buildpack/java@sha256:49117cd7d145353ff566879a752630041f61572923dd722abff9c44dbc9b0daa
  - image: registry.pivotal.io/tanzu-nodejs-buildpack/nodejs@sha256:80b68add67f8f06ff7a121062df13a12de7eb4ae1d8bf53bae1bf72e543f1c06
  - image: registry.pivotal.io/tanzu-java-native-image-buildpack/java-native-image@sha256:60f78322924812c452d4137707462254ec499555fdcadcb1e0a9bde5dc39e61e
  - image: registry.pivotal.io/tbs-dependencies/tanzu-buildpacks_dotnet-core@sha256:d8ce44165166da988cc334e13956838623d233861b57eaf011d43535b1b86bf4
  - image: registry.pivotal.io/tbs-dependencies/tanzu-buildpacks_php@sha256:7af56f344798284732ddc33a1d5d6973d1635d3f0e9b8d960e027b08ab3894ad
  - image: registry.pivotal.io/tbs-dependencies/tanzu-buildpacks_nginx@sha256:e0363a5e6ce01f0935df65d6f89994a91bee63c2f25249c62a84788f53eb4346
  - image: registry.pivotal.io/tbs-dependencies/tanzu-buildpacks_httpd@sha256:892c824d98afb32198cd5b303098eee5be2600f076455bd8f7da3a34adf2c340
  - image: registry.pivotal.io/tbs-dependencies/paketo-buildpacks_procfile@sha256:861d9c93924dd1db3fbe6663754da603398931cdc4dee3da5c057ffa65cb383d
stacks:
- name: tiny
  buildImage:
    image: registry.pivotal.io/tbs-dependencies/build-tiny@sha256:72d129c5a78ea8664ad599fba5774d7d2934922b880c7ef274ffb9c3c1fa487e
  runImage:
    image: registry.pivotal.io/tbs-dependencies/run-tiny@sha256:8d57a6233d9b3a2e51b1c7d557c0ec63e1084cf4aa5ffceb2de6a1e9382463ba
- name: base
  buildImage:
    image: registry.pivotal.io/tbs-dependencies/build-base@sha256:fc7812da175030b274d44c50101e76b093f7fdbc673a25dd7e8be3f85815fdb1
  runImage:
    image: registry.pivotal.io/tbs-dependencies/run-base@sha256:d82af59ce063da1d04e47c19db16179a26b9c6932e5c0ef195a134de755064ea
- name: full
  buildImage:
    image: registry.pivotal.io/tbs-dependencies/build-full@sha256:fcdd323c9b77d9b622f11dc9e68a2ef09201afe605c2fccfe1e9c7f878a683be
  runImage:
    image: registry.pivotal.io/tbs-dependencies/run-full@sha256:16515ead81f41ecdb8b391ab931853138425bb4b75486c0bc434531fb67ca2e5
clusterBuilders:
- name: base
  stack: base
  store: default
  order:
  - group:
    - id: tanzu-buildpacks/dotnet-core
  - group:
    - id: tanzu-buildpacks/nodejs
  - group:
    - id: tanzu-buildpacks/go
  - group:
    - id: tanzu-buildpacks/php
  - group:
    - id: tanzu-buildpacks/nginx
  - group:
    - id: tanzu-buildpacks/httpd
  - group:
    - id: tanzu-buildpacks/java-native-image
  - group:
    - id: tanzu-buildpacks/java
  - group:
    - id: paketo-buildpacks/procfile
- name: full
  stack: full
  store: default
  order:
  - group:
    - id: tanzu-buildpacks/dotnet-core
  - group:
    - id: tanzu-buildpacks/nodejs
  - group:
    - id: tanzu-buildpacks/go
  - group:
    - id: tanzu-buildpacks/php
  - group:
    - id: tanzu-buildpacks/nginx
  - group:
    - id: tanzu-buildpacks/httpd
  - group:
    - id: tanzu-buildpacks/java-native-image
  - group:
    - id: tanzu-buildpacks/java
  - group:
    - id: paketo-buildpacks/procfile
- name: tiny
  stack: tiny
  store: default
  order:
  - group:
    - id: tanzu-buildpacks/go
  - group:
    - id: tanzu-buildpacks/java-native-image
  - group:
    - id: paketo-buildpacks/procfile
